CREATE DATABASE COLLEGE;
#DROP DATABASE COLLEGE

USE COLLEGE;



CREATE TABLE STUDENT(studId INTEGER(5) not NULL, 
 name VARCHAR(255),  city VARCHAR(255),  age INTEGER,  PRIMARY KEY (studId));
 
 INSERT INTO STUDENT VALUES (100, 'Zara', 'Ali', 18);
 INSERT INTO STUDENT VALUES (101, 'Zara', 'Ali', 18);
 INSERT INTO STUDENT MARKSSTUDENTVALUES (102, 'Zara', 'Ali', 18);
 
 UPDATE STUDENT
	SET age = 30
		WHERE studId=101;
 
 #DROP TABLE STUDENT #table structure and constraints will be dropped
#TRUNCATE  TABLE STUDENT

 #DELETE  FROM STUDENT
#DELETE  FROM STUDENT WHERE ID=102

CREATE TABLE MARKS(id INTEGER(5) not NULL, 
subject VARCHAR(10),  marks INTEGER(5),  studId INTEGER(5),  PRIMARY KEY (id));

 INSERT INTO MARKS VALUES (3, 'English', 50, 101);
 INSERT INTO MARKS VALUES (4, 'Tamil', 55, 101);
 INSERT INTO MARKS VALUES (8, null, 60, 101);
  INSERT INTO MARKS VALUES (6, null, 70, 101);
   INSERT INTO MARKS VALUES (7, null, 80, 101);
 
 SELECT * FROM STUDENT
 SELECT * FROM MARKS
 SELECT * FROM MARKS WHERE subject IS NULL
SELECT * FROM MARKS WHERE marks =60. 			  #SINGLE EXACT MATCH
SELECT * FROM MARKS WHERE subject LIKE '%ng%'     #PARTIAL MATCHING
SELECT * FROM MARKS WHERE marks IN (60, 80)       #GET SET OF VALUES - MULTI EXACT MATCH
SELECT * FROM MARKS WHERE marks BETWEEN 60 and 80 #RANGE OF VALUES




 
 SELECT name FROM STUDENT UNION SELECT subject FROM MARKS #prints both in single row omitting duplicates
  SELECT name FROM STUDENT UNION ALL SELECT subject FROM MARKS #includes duplicates



